# Generated by Django 3.2.5 on 2021-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_notified',
            field=models.BooleanField(default=False, help_text='When true, the user has been notified that their account is approved'),
        ),
    ]
