# Generated by Django 3.2.5 on 2021-07-23 04:49

from django.db import migrations, models
import django.db.models.deletion
import fahari.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_facility_is_fahari_facility'),
        ('users', '0006_user_approval_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(default=fahari.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, to='common.organisation'),
        ),
    ]
