# Generated by Django 3.2.6 on 2021-10-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_dashboard', 'Can View Dashboard'), ('can_view_about', 'Can View About Page'), ('can_export_data', 'Can Export Data'), ('can_import_data', 'Can Import Data')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
