# Generated by Django 3.2.9 on 2021-11-10 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import fahari.sims.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('query', models.TextField(verbose_name='Question')),
                ('answer_type', models.CharField(choices=[('true_false', 'True/False'), ('yes_no', 'Yes/No'), ('number', 'Number'), ('short_answer', 'Short Answer'), ('paragraph', 'Long Answer'), ('radio_option', 'Select One'), ('select_list', 'Select Multiple'), ('dependent', 'Depends on Another Answer'), ('none', 'Not Applicable')], default='short_answer', help_text='Expected answer type', max_length=15)),
                ('precedence', models.PositiveIntegerField()),
                ('numbering', models.CharField(default='(i)', max_length=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sims_question_related', to='common.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_questions', to='sims.question')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.sims.models.QuestionManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Group title')),
                ('precedence', models.PositiveIntegerField()),
                ('numbering', models.CharField(default='(a)', max_length=5)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sims_questiongroup_related', to='common.organisation')),
                ('question_groups', models.ManyToManyField(blank=True, related_name='_sims_questiongroup_question_groups_+', to='sims.QuestionGroup')),
                ('questions', models.ManyToManyField(blank=True, related_name='question_groups', to='sims.Question')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.sims.models.QuestionGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sims_questionnaire_related', to='common.organisation')),
                ('question_groups', models.ManyToManyField(related_name='questionnaires', to='sims.QuestionGroup')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finish_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sims_questionnaireresponses_related', to='common.organisation')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sims.questionnaire')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('response', models.JSONField(default=dict)),
                ('answered_on', models.DateTimeField(default=datetime.datetime.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sims_questionanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='sims.question')),
                ('questionnaire_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='sims.questionnaireresponses')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionanswer',
            constraint=models.UniqueConstraint(fields=('question', 'questionnaire_response'), name='unique_together_question_and_questionnaire_response'),
        ),
    ]
