# Generated by Django 3.2.9 on 2021-11-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent question that this question is part of.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_questions', to='sims.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='precedence',
            field=models.PositiveSmallIntegerField(help_text="The rank of a question within it's container. Used to position the question when rendering a questionnaire."),
        ),
        migrations.AlterField(
            model_name='question',
            name='precedence_display_type',
            field=models.CharField(blank=True, choices=[('bullet', 'Bullets'), ('numbered_td', 'Numbered with a trailing dot, E.g. 1., 2., 3.'), ('lower_case_letters_tcb', 'Lower case letter with trailing closing bracket, E.g. a), b), c)')], help_text='The precedence display type of a "container". This sets the precedence display type for all the child elements of this container but not the container itself.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent question group that this question group belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_question_groups', to='sims.questiongroup'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='precedence',
            field=models.PositiveSmallIntegerField(help_text='The rank of a question group within it\'s "container". Used to position the question group when rendering a questionnaire.'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='precedence_display_type',
            field=models.CharField(blank=True, choices=[('bullet', 'Bullets'), ('numbered_td', 'Numbered with a trailing dot, E.g. 1., 2., 3.'), ('lower_case_letters_tcb', 'Lower case letter with trailing closing bracket, E.g. a), b), c)')], help_text='The precedence display type of a "container". This sets the precedence display type for all the child elements of this container but not the container itself.', max_length=150, null=True),
        ),
    ]
