# Generated by Django 3.2.7 on 2021-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_alter_questiongroup_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('true_false', 'True/False'), ('yes_no', 'Yes/No'), ('number', 'Whole Number'), ('fraction', 'Fractional Number'), ('short_answer', 'Short Answer'), ('radio_option', 'Select One'), ('select_list', 'Select Multiple'), ('dependent', 'Dependent on Another Answer'), ('ratio', 'Ratio'), ('none', 'Not Applicable')], default='short_answer', help_text='Expected answer type', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
