# Generated by Django 3.2.7 on 2021-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_alter_questiongroup_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
