steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/sghi/mle:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/sghi/mle:$COMMIT_SHA"]

  # Deploy an image from Container Registry to Cloud Run
  # TODO POSTGRES_HOST
  # TODO POSTGRES_PORT
  # TODO POSTGRES_DB
  # TODO POSTGRES_USER
  # TODO POSTGRES_PASSWORD
  # TODO DATABASE_URL
  # TODO DJANGO_SECRET_KEY
  # TODO DJANGO_ADMIN_URL
  # TODO DJANGO_ALLOWED_HOSTS
  # TODO DJANGO_SECURE_BROWSER_XSS_FILTER
  # TODO DJANGO_SECURE_SSL_REDIRECT
  # TODO DJANGO_SECURE_CONTENT_TYPE_NOSNIFF
  # TODO DJANGO_SECURE_FRAME_DENY
  # TODO DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS
  # TODO DJANGO_SESSION_COOKIE_HTTPONLY
  # TODO DJANGO_SESSION_COOKIE_SECURE
  # TODO DJANGO_SERVER_EMAIL
  # TODO DJANGO_DEFAULT_FROM_EMAIL
  # TODO DJANGO_EMAIL_SUBJECT_PREFIX
  # TODO DJANGO_SENTRY_LOG_LEVEL
  # TODO SENTRY_TRACES_SAMPLE_RATE
  # TODO MAILGUN_API_KEY
  # TODO MAILGUN_DOMAIN
  # TODO MAILGUN_API_URL
  # TODO DJANGO_GCP_STORAGE_BUCKET_NAME
  # TODO DJANGO_ACCOUNT_ALLOW_REGISTRATION
  # TODO SENTRY_DSN=https://a05704bb311943c1b1d737b60b64c09c@errors.bewell.co.ke/6

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'mle',
      '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/sghi/mle:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--update-env-vars', 'SENTRY_ENVIRONMENT=prod,COMPRESS_ENABLED=true,DJANGO_DEBUG=false,USE_DOCKER=yes,DJANGO_READ_DOT_ENV_FILE=False,DJANGO_SETTINGS_MODULE=config.settings.production,DJANGO_SECURE_SSL_REDIRECT=False,WEB_CONCURRENCY=4'
  ]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/sghi/mle:$COMMIT_SHA"
