#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
>&2 echo 'Ran database migrations...'

python manage.py createcachetable
>&2 echo 'Created the cache table...'

/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:$PORT --chdir=/app -k uvicorn.workers.UvicornWorker
