# Generated by Django 3.2.5 on 2021-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='When true, the user is able to log in to the main website (and vice versa)'),
        ),
    ]
