# Generated by Django 3.1.12 on 2021-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210714_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ('-updated', '-created'), 'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='updated_by',
            field=models.UUIDField(blank=True),
        ),
    ]
