# Generated by Django 3.1.12 on 2021-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_auto_20210714_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityattachment",
            name="size",
            field=models.IntegerField(
                blank=True, help_text="The size of the attachment in bytes", null=True
            ),
        ),
    ]
