# Generated by Django 3.2.5 on 2021-07-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_system_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="beds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facility",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="constituency",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="cots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_owner",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type_category",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="keph_level",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="open_late_night",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="open_public_holidays",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="open_weekends",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="open_whole_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="operation_status",
            field=models.CharField(default="Operational", max_length=24),
        ),
        migrations.AddField(
            model_name="facility",
            name="owner_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="public_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="registration_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="regulatory_body",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="sub_county",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="ward",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="county",
            field=models.CharField(
                choices=[
                    ("47_NAIROBI_CITY", "Nairobi City"),
                    ("46_NYAMIRA", "Nyamira"),
                    ("45_KISII", "Kisii"),
                    ("44_MIGORI", "Migori"),
                    ("43_HOMA_BAY", "Homa Bay"),
                    ("42_KISUMU", "Kisumu"),
                    ("41_SIAYA", "Siaya"),
                    ("40_BUSIA", "Busia"),
                    ("39_BUNGOMA", "Bungoma"),
                    ("38_VIHIGA", "Vihiga"),
                    ("37_KAKAMEGA", "Kakamega"),
                    ("36_BOMET", "Bomet"),
                    ("35_KERICHO", "Kericho"),
                    ("34_KAJIADO", "Kajiado"),
                    ("33_NAROK", "Narok"),
                    ("32_NAKURU", "Nakuru"),
                    ("31_LAIKIPIA", "Laikipia"),
                    ("30_BARINGO", "Baringo"),
                    ("29_NANDI", "Nandi"),
                    ("28_ELGEYO_MARAKWET", "Elgeyo/Marakwet"),
                    ("27_UASIN_GISHU", "Uasin Gishu"),
                    ("26_TRANS_NZOIA", "Trans Nzoia"),
                    ("25_SAMBURU", "Samburu"),
                    ("24_WEST_POKOT", "West Pokot"),
                    ("23_TURKANA", "Turkana"),
                    ("22_KIAMBU", "Kiambu"),
                    ("21_MURANGA", "Murang'a"),
                    ("20_KIRINYAGA", "Kirinyaga"),
                    ("19_NYERI", "Nyeri"),
                    ("18_NYANDARUA", "Nyandarua"),
                    ("17_MAKUENI", "Makueni"),
                    ("16_MACHAKOS", "Machakos"),
                    ("15_KITUI", "Kitui"),
                    ("14_EMBU", "Embu"),
                    ("13_THARAKA_NITHI", "Tharaka-Nithi"),
                    ("12_MERU", "Meru"),
                    ("11_ISIOLO", "Isiolo"),
                    ("10_MARSABIT", "Marsabit"),
                    ("09_MANDERA", "Mandera"),
                    ("08_WAJIR", "Wajir"),
                    ("07_GARISSA", "Garissa"),
                    ("06_TAITA_TAVETA", "Taita/Taveta"),
                    ("05_LAMU", "Lamu"),
                    ("04_TANA_RIVER", "Tana River"),
                    ("03_KILIFI", "Kilifi"),
                    ("02_KWALE", "Kwale"),
                    ("01_MOMBASA", "Mombasa"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
