# Generated by Django 3.2.5 on 2021-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210719_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='county',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_owner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
