# Generated by Django 3.2.5 on 2021-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210719_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
