# Generated by Django 3.2.5 on 2021-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_facility_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type_category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
