# Generated by Django 3.2.5 on 2021-07-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_facility_facility_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='facility',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
