# Generated by Django 3.2.5 on 2021-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_facilityuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_fahari_facility',
            field=models.BooleanField(default=True),
        ),
    ]
