# Generated by Django 3.2.5 on 2021-07-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_facility_is_fahari_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='mfl_code',
            field=models.IntegerField(help_text='MFL Code', unique=True),
        ),
    ]
