# Generated by Django 3.2.5 on 2021-07-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_facility_mfl_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityuser',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='data',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='size',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='title',
        ),
    ]
