# Generated by Django 3.2.6 on 2021-09-11 14:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0020_alter_system_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='pattern',
            field=models.CharField(choices=[('poc', 'Point of Care'), ('rde', 'Retrospective Data Entry'), ('hybrid', 'Hybrid'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='UserFacilityAllotment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('allotment_type', models.CharField(choices=[('facility', 'By Facility'), ('region', 'By Region'), ('both', 'By Both Facility and Region')], max_length=100)),
                ('region_type', models.CharField(blank=True, choices=[('county', 'County'), ('constituency', 'Constituency'), ('sub_county', 'Sub County'), ('ward', 'Ward')], max_length=20, null=True)),
                ('counties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Kajiado', 'Kajiado')], max_length=150, null=True), blank=True, help_text='All the facilities in the selected counties will be allocated to the selected user.', null=True, size=None)),
                ('constituencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Dagoretti North', 'Dagoretti North'), ('Dagoretti South', 'Dagoretti South'), ('Embakasi Central', 'Embakasi Central'), ('Embakasi East', 'Embakasi East'), ('Embakasi North', 'Embakasi North'), ('Embakasi South', 'Embakasi South'), ('Embakasi West', 'Embakasi West'), ('Kajiado Central', 'Kajiado Central'), ('Kajiado East', 'Kajiado East'), ('Kajiado North', 'Kajiado North'), ('Kajiado West', 'Kajiado West'), ('Kamukunji', 'Kamukunji'), ('Kasarani', 'Kasarani'), ('Kibra', 'Kibra'), ('Langata', 'Langata'), ('Magadi', 'Magadi'), ('Makadara', 'Makadara'), ('Mathare', 'Mathare'), ('Roysambu', 'Roysambu'), ('Ruaraka', 'Ruaraka'), ('Starehe', 'Starehe'), ('Westlands', 'Westlands')], max_length=150, null=True), blank=True, help_text='All the facilities in the selected constituencies will be allocated to the selected user.', null=True, size=None)),
                ('sub_counties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Dagoretti North', 'Dagoretti North'), ('Dagoretti South', 'Dagoretti South'), ('Embakasi Central', 'Embakasi Central'), ('Embakasi East', 'Embakasi East'), ('Embakasi North', 'Embakasi North'), ('Embakasi South', 'Embakasi South'), ('Embakasi West', 'Embakasi West'), ('Kajiado Central', 'Kajiado Central'), ('Kajiado East', 'Kajiado East'), ('Kajiado North', 'Kajiado North'), ('Kajiado West', 'Kajiado West'), ('Kamukunji', 'Kamukunji'), ('Kasarani', 'Kasarani'), ('Kibra', 'Kibra'), ('Langata', 'Langata'), ('Loitokitok', 'Loitokitok'), ('Makadara', 'Makadara'), ('Mathare', 'Mathare'), ('Roysambu', 'Roysambu'), ('Ruaraka', 'Ruaraka'), ('Starehe', 'Starehe'), ('Westlands', 'Westlands')], max_length=150, null=True), blank=True, help_text='All the facilities in the selected sub counties will be allocated to the selected user.', null=True, size=None)),
                ('wards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Airbase', 'Airbase'), ('Babandogo', 'Babandogo'), ('California', 'California'), ('Clay City', 'Clay City'), ('Dalalekutuk', 'Dalalekutuk'), ('Dandora Area I', 'Dandora Area I'), ('Dandora Area II', 'Dandora Area II'), ('Dandora Area III', 'Dandora Area III'), ('Dandora Area Iv', 'Dandora Area Iv'), ('Eastleigh North', 'Eastleigh North'), ('Eastleigh South', 'Eastleigh South'), ('Embakasi', 'Embakasi'), ('Entonet/Lenkism', 'Entonet/Lenkism'), ("Ewuaso Oo Nkidong'i", "Ewuaso Oo Nkidong'i"), ('Gatini', 'Gatini'), ('Githurai', 'Githurai'), ('Harambee', 'Harambee'), ('Hospital', 'Hospital'), ('Huruma', 'Huruma'), ('Ildamat', 'Ildamat'), ('Iloodokilani', 'Iloodokilani'), ('Imara Daima', 'Imara Daima'), ('Imaroro', 'Imaroro'), ('Imbrikani/Eselelnkei', 'Imbrikani/Eselelnkei'), ('Kabiro', 'Kabiro'), ('Kahawa', 'Kahawa'), ('Kahawa West', 'Kahawa West'), ('Kangemi', 'Kangemi'), ('Kaputiei North', 'Kaputiei North'), ('Karen', 'Karen'), ('Kariobangi South', 'Kariobangi South'), ('Karioboangi North', 'Karioboangi North'), ('Karura', 'Karura'), ('Kasarani', 'Kasarani'), ('Kawangware', 'Kawangware'), ('Kayole Central', 'Kayole Central'), ('Kayole North', 'Kayole North'), ('Kayole South', 'Kayole South'), ('Keekonyokie', 'Keekonyokie'), ('Kenyawa-poka', 'Kenyawa-poka'), ('Kiamaiko', 'Kiamaiko'), ('Kileleshwa', 'Kileleshwa'), ('Kilimani', 'Kilimani'), ('Kimana', 'Kimana'), ('Kitengela', 'Kitengela'), ('Kitisuru', 'Kitisuru'), ('Komarock', 'Komarock'), ('Korogocho', 'Korogocho'), ('Kuku', 'Kuku'), ('Kwa Njenga', 'Kwa Njenga'), ('Kwa Rueben', 'Kwa Rueben'), ('Kware', 'Kware'), ('Laini Saba', 'Laini Saba'), ('Landimawe', 'Landimawe'), ('Lindi', 'Lindi'), ('Lower Savannah', 'Lower Savannah'), ('Lucky Summer', 'Lucky Summer'), ('Mabatini', 'Mabatini'), ('Magadi', 'Magadi'), ("MakinaSarang'ombe", "MakinaSarang'ombe"), ('Makongeni', 'Makongeni'), ('Maringo/Hamza', 'Maringo/Hamza'), ('Maringo/Hamza', 'Maringo/Hamza'), ('Matapato North', 'Matapato North'), ('Matapato South', 'Matapato South'), ('Mathare North', 'Mathare North'), ('Matopeni/Spring Valley', 'Matopeni/Spring Valley'), ('Mihango', 'Mihango'), ('Mosiro', 'Mosiro'), ('Mountain View', 'Mountain View'), ('Mowlem', 'Mowlem'), ('Mugumo-ini', 'Mugumo-ini'), ('Mutu-Ini', 'Mutu-Ini'), ('Mwiki', 'Mwiki'), ('Nairobi Central', 'Nairobi Central'), ('Nairobi South', 'Nairobi South'), ('Nairobi West', 'Nairobi West'), ('Ngando', 'Ngando'), ('Ngara', 'Ngara'), ('Ngei', 'Ngei'), ('Ngong', 'Ngong'), ('Njiru', 'Njiru'), ('Nkaimurunya', 'Nkaimurunya'), ('Nyayo Highrise', 'Nyayo Highrise'), ('Olkeri', 'Olkeri'), ('Oloolua', 'Oloolua'), ('Oloosirkon/Sholinke', 'Oloosirkon/Sholinke'), ('Ongata Rongai', 'Ongata Rongai'), ('Pangani', 'Pangani'), ('Parklands/Highridge', 'Parklands/Highridge'), ('Pipeline', 'Pipeline'), ('Pumwani', 'Pumwani'), ('Purko', 'Purko'), ('Riruta', 'Riruta'), ('Rombo', 'Rombo'), ('Roysambu', 'Roysambu'), ('Ruai', 'Ruai'), ('South C', 'South C'), ('Umoja I', 'Umoja I'), ('Umoja II', 'Umoja II'), ('Upper Savannah', 'Upper Savannah'), ('Utalii', 'Utalii'), ('Utawala', 'Utawala'), ('Uthiru/Ruthimitu', 'Uthiru/Ruthimitu'), ('Viwandani', 'Viwandani'), ('Waithaka', 'Waithaka'), ('Woodley/Kenyatta Golf Course', 'Woodley/Kenyatta Golf Course'), ('Zimmerman', 'Zimmerman'), ('Ziwani/Kariokor', 'Ziwani/Kariokor')], max_length=150, null=True), blank=True, help_text='All the facilities in the selected wards will be allocated to the selected user.', null=True, size=None)),
                ('facilities', models.ManyToManyField(blank=True, to='common.Facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_userfacilityallotment_related', to='common.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
    ]
