# Generated by Django 3.2.5 on 2021-07-19 09:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_system_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgramUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('attendees', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('comments', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.activity')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_weeklyprogramupdate_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteMentorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('day', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('objective', models.TextField()),
                ('pick_up_point', models.TextField()),
                ('drop_off_point', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_sitementorship_related', to='common.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-day', '-end', '-start', 'site__name'),
            },
        ),
        migrations.CreateModel(
            name='OperationalArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_operationalarea_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
                ('clients_booked', models.IntegerField()),
                ('kept_appointment', models.IntegerField()),
                ('missed_appointment', models.IntegerField()),
                ('came_early', models.IntegerField()),
                ('unscheduled', models.IntegerField()),
                ('new_ft', models.IntegerField()),
                ('ipt_new_adults', models.IntegerField()),
                ('ipt_new_paeds', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_dailyupdate_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('activity', models.TextField(help_text='Activity as budgeted for')),
                ('planned_date', models.DateField(help_text='Planned date for the activity')),
                ('requested_date', models.DateField(help_text='Date requested')),
                ('procurement_date', models.DateField(help_text='Date received by procurement')),
                ('finance_approval_date', models.DateField(help_text='Date received by Finance for approvals')),
                ('final_approval_date', models.DateField(help_text='Date approved by COP/DCOP/FAD')),
                ('done_date', models.DateField(help_text='Date when activity/procurement done')),
                ('invoiced_date', models.DateField(help_text='Date when payment invoice was submitted to Finance')),
                ('remarks', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_activitylog_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-requested_date', '-planned_date', '-procurement_date'),
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.operationalarea'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_activity_related', to='common.organisation'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
