# Generated by Django 3.2.5 on 2021-07-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20210719_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitysystem',
            options={'ordering': ('facility__name', 'system__name', '-version', '-updated', '-created')},
        ),
    ]
