# Generated by Django 3.2.5 on 2021-07-26 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_facility_mfl_code'),
        ('ops', '0003_alter_facilitysystem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceiptVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('pack_size', models.TextField()),
                ('delivery_note_number', models.CharField(max_length=64)),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=10)),
                ('batch_number', models.CharField(max_length=64)),
                ('expiry_date', models.DateField()),
                ('comments', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_stockreceiptverification_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
    ]
