# Generated by Django 3.2.5 on 2021-07-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_stockreceiptverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ('-planned_date', '-requested_date', '-procurement_date')},
        ),
        migrations.AlterModelOptions(
            name='dailyupdate',
            options={'ordering': ('-date', 'facility__name')},
        ),
    ]
