# Generated by Django 3.2.5 on 2021-07-27 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_auto_20210727_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='done_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Date when activity/procurement done'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='final_approval_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Date approved by COP/DCOP/FAD'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='finance_approval_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Date received by Finance for approvals'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='invoiced_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Date when payment invoice was submitted to Finance'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='planned_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Planned date for the activity'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='procurement_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Date received by procurement'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='requested_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Date requested'),
        ),
        migrations.AlterField(
            model_name='stockreceiptverification',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
