# Generated by Django 3.2.5 on 2021-07-28 14:59

import datetime
from django.db import migrations, models
import fahari.ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_auto_20210727_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitementorship',
            options={'ordering': ('-end', '-start', 'site__name')},
        ),
        migrations.AlterField(
            model_name='sitementorship',
            name='day',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='sitementorship',
            name='end',
            field=models.TimeField(default=fahari.ops.models.default_end_time),
        ),
        migrations.AlterField(
            model_name='sitementorship',
            name='start',
            field=models.TimeField(default=fahari.ops.models.default_start_time),
        ),
    ]
