# Generated by Django 3.2.5 on 2021-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_auto_20210728_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitementorship',
            options={'ordering': ('-day', 'site__name')},
        ),
        migrations.RemoveField(
            model_name='sitementorship',
            name='end',
        ),
        migrations.RemoveField(
            model_name='sitementorship',
            name='start',
        ),
        migrations.AddField(
            model_name='sitementorship',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
