# Generated by Django 3.2.5 on 2021-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_auto_20210728_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitementorship',
            name='duration',
            field=models.DurationField(default='08:00:00', help_text="HH:MM:SS e.g '08:00:00' for 8 hours"),
        ),
    ]
