# Generated by Django 3.2.5 on 2021-07-28 17:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0010_auto_20210728_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('staff', 'date')},
        ),
    ]
