# Generated by Django 3.2.5 on 2021-07-28 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210727_1306'),
        ('ops', '0011_auto_20210728_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='comments',
        ),
        migrations.AlterField(
            model_name='weeklyprogramupdate',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='WeeklyProgramUpdateDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.activity')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_weeklyprogramupdatedetail_related', to='common.organisation')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.weeklyprogramupdate')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
    ]
