# Generated by Django 3.2.6 on 2021-08-11 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_auto_20210728_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogramupdate',
            name='attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Use commas to separate attendees names', size=None),
        ),
    ]
