# Generated by Django 3.2.6 on 2021-08-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_alter_weeklyprogramupdate_attendees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitysystemticket',
            options={'ordering': ('facility_system__facility__name', 'facility_system__system__name', '-raised', '-resolved'), 'permissions': [('can_resolve_ticket', 'Can Resolve Ticket')]},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('-date', '-approved_at', 'staff__name'), 'permissions': [('can_approve_timesheet', 'Can Approve Timesheet')]},
        ),
    ]
