# Generated by Django 3.2.6 on 2021-08-19 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.ops.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210727_1306'),
        ('ops', '0014_auto_20210811_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceiptverification',
            name='description',
            field=models.TextField(default='-'),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='-')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_commodity_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockreceiptverification',
            name='commodity',
            field=models.ForeignKey(default=fahari.ops.models.default_commodity, on_delete=django.db.models.deletion.PROTECT, to='ops.commodity'),
        ),
    ]
