# Generated by Django 3.2.6 on 2021-08-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_auto_20210819_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='notes',
            field=models.TextField(default='-'),
        ),
    ]
