# Generated by Django 3.2.6 on 2021-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_weeklyprogramupdate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysystemticket',
            name='resolve_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
