# Generated by Django 3.2.6 on 2021-09-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_auto_20210901_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyprogramupdate',
            old_name='file',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='weeklyprogramupdate',
            old_name='notes',
            new_name='description',
        ),
    ]
