# Generated by Django 3.2.6 on 2021-09-07 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_system_pattern'),
        ('ops', '0021_stockreceiptverification_delivery_note_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoMCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('measure_type', models.CharField(choices=[('length', 'Length'), ('time', 'Time'), ('unit', 'Unit'), ('volume', 'Volume'), ('weight', 'Weight')], help_text='Type of Measure', max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_uomcategory_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Unit of Measure')),
                ('category', models.ForeignKey(help_text='Conversion between Units of Measure can only occur if they belong to the same category.', on_delete=django.db.models.deletion.PROTECT, to='ops.uomcategory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_uom_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.uom'),
        ),
        migrations.AddField(
            model_name='stockreceiptverification',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.uom', verbose_name='Pack size'),
        ),
        migrations.RemoveField(
            model_name='stockreceiptverification',
            name='pack_size',
        ),
    ]
