# Generated by Django 3.2.7 on 2021-09-13 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_system_pattern'),
        ('ops', '0023_auto_20210908_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDeviceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('device_requested', models.CharField(default='', max_length=50)),
                ('request_type', models.CharField(choices=[('NEW', 'New'), ('REPLACEMENT', 'Replacement'), ('REPAIR', 'Repair')], default='NEW', max_length=20)),
                ('request_details', models.TextField(default='-')),
                ('date_requested', models.DateField(default=datetime.datetime.today)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_facilitydevicerequest_related', to='common.organisation')),
            ],
            options={
                'ordering': ('facility__name', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='FacilityDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('number_of_devices', models.PositiveSmallIntegerField(default=0)),
                ('number_of_ups', models.PositiveSmallIntegerField(default=0, verbose_name='Number of UPS')),
                ('server_specification', models.TextField(default='-')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_facilitydevice_related', to='common.organisation')),
            ],
            options={
                'ordering': ('facility__name', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='FacilityNetworkStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('has_network', models.BooleanField(default=True)),
                ('has_internet', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_facilitynetworkstatus_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', 'facility__name'),
                'unique_together': {('facility',)},
            },
        ),
    ]
