# Generated by Django 3.2.7 on 2021-09-13 09:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_system_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0024_facilitydevice_facilitydevicerequest_facilitynetworkstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Incidence title')),
                ('details', models.TextField(default='-', verbose_name='Incidence details')),
                ('reported_on', models.DateField(default=datetime.datetime.today, editable=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_securityincidence_related', to='common.organisation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('facility__name', '-updated'),
            },
        ),
    ]
