# Generated by Django 3.2.7 on 2021-09-14 07:59

from django.db import migrations, models
import fahari.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_securityincidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysystem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=fahari.common.models.get_directory, verbose_name='Attach File or Photo'),
        ),
        migrations.AddField(
            model_name='facilitysystem',
            name='release_notes',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='facilitysystem',
            name='trainees',
            field=models.TextField(default='-'),
        ),
    ]
