# Generated by Django 3.2.6 on 2021-09-14 11:03

from django.db import migrations
import fahari.common.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_securityincidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uom',
            options={'ordering': ('name', '-updated', '-created')},
        ),
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='activitylog',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='commodity',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dailyupdate',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facilitydevice',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facilitydevicerequest',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facilitynetworkstatus',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facilitysystem',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facilitysystemticket',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='operationalarea',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='securityincidence',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sitementorship',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stockreceiptverification',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timesheet',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='uom',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='uomcategory',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='weeklyprogramupdate',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='weeklyprogramupdatedetail',
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
    ]
