# Generated by Django 3.2.6 on 2021-09-19 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import fahari.common.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_auto_20210914_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysystem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=fahari.common.models.utils.get_directory, verbose_name='Attach File or Photo'),
        ),
        migrations.AddField(
            model_name='facilitysystem',
            name='release_notes',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='facilitysystem',
            name='trainees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Use commas to separate trainees names', size=None),
        ),
        migrations.AlterField(
            model_name='stockreceiptverification',
            name='delivery_note_image',
            field=models.ImageField(blank=True, null=True, upload_to=fahari.common.models.utils.get_directory, verbose_name='Delivery note photograph'),
        ),
    ]
