# Generated by Django 3.2.7 on 2021-09-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_auto_20210914_1059'),
        ('ops', '0026_auto_20210914_1403'),
    ]

    operations = [
    ]
