# Generated by Django 3.2.7 on 2021-09-22 12:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0027_auto_20210919_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgramUpdateComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(default='-')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_weeklyprogramupdatecomment_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='weeklyprogramupdate',
            options={'ordering': ('facility__name', 'operation_area', 'status')},
        ),
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='assigned_persons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Use commas to separate assigned persons names', null=True, size=None),
        ),
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.facility'),
        ),
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='operation_area',
            field=models.CharField(choices=[('admin', 'Administration'), ('finance', 'Finance'), ('awarding', 'Awarding'), ('subgranting', 'Subgranting'), ('sii', 'Strategic Information System'), ('program', 'Program')], default='program', help_text='Operation area', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('complete', 'Complete')], default='in_progress', help_text='Status', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyprogramupdate',
            unique_together={('facility', 'operation_area', 'date_created')},
        ),
        migrations.DeleteModel(
            name='WeeklyProgramUpdateDetail',
        ),
        migrations.AddField(
            model_name='weeklyprogramupdatecomment',
            name='weekly_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.weeklyprogramupdate'),
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='title',
        ),
    ]
