# Generated by Django 3.2.7 on 2021-09-14 13:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_merge_0026_auto_20210914_1059_0026_auto_20210914_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitysystem',
            name='trainees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Use commas to separate trainees names', size=None),
        ),
    ]
