# Generated by Django 3.2.6 on 2021-09-23 14:05

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import fahari.common.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20210919_1704'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='facilitysystem',
            managers=[
                ('objects', fahari.common.models.base_models.LinkedRecordsManager(('facility', 'system'))),
            ],
        ),
        migrations.AddField(
            model_name='facilitysystem',
            name='previous_node',
            field=models.OneToOneField(blank=True, db_column='previous_node', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_facilitysystem_next_node', to='ops.facilitysystem'),
        ),
        migrations.AddConstraint(
            model_name='facilitysystem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('previous_node',), name='unique_ops.facilitysystem_previous_node'),
        ),
        migrations.RemoveConstraint(
            model_name='facilitysystem',
            name='unique_ops.facilitysystem_previous_node',
        ),
        migrations.AddConstraint(
            model_name='facilitysystem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('facility', 'system', 'previous_node'), name='unique_ops.facilitysystem_previous_node'),
        ),
    ]
