# Generated by Django 3.2.7 on 2021-09-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0028_alter_facilitysystem_trainees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyprogramupdatedetail',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdatedetail',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdatedetail',
            name='parent',
        ),
        migrations.DeleteModel(
            name='WeeklyProgramUpdate',
        ),
        migrations.DeleteModel(
            name='WeeklyProgramUpdateDetail',
        ),
    ]
