# Generated by Django 3.2.7 on 2021-09-15 14:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20210914_1639'),
        ('ops', '0029_auto_20210915_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgramUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('operation_area', models.CharField(choices=[('admin', 'Administration'), ('finance', 'Finance'), ('awarding', 'Awarding'), ('subgranting', 'Subgranting'), ('sii', 'Strategic Information System'), ('program', 'Program')], help_text='Operation area', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('complete', 'Complete')], help_text='Status', max_length=20)),
                ('assigned_persons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Use commas to separate assigned persons names', null=True, size=None)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_weeklyprogramupdate_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-operation_area', 'status'),
                'unique_together': {('facility', 'operation_area', 'date_created')},
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProgramUpdateCommentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('comments', models.TextField(default='-')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_weeklyprogramupdatecommentline_related', to='common.organisation')),
                ('weekly_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.weeklyprogramupdate')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
    ]
