# Generated by Django 3.2.7 on 2021-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0029_auto_20211006_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogramupdate',
            name='operation_area',
            field=models.CharField(choices=[('admin', 'Administration'), ('finance', 'Finance'), ('awarding', 'Awarding'), ('subgranting', 'Subgranting'), ('sii', 'Strategic Information System'), ('program', 'Program')], default='program', help_text='Task Area of Operation', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyprogramupdate',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('complete', 'Complete')], default='in_progress', help_text='Task status', max_length=20),
        ),
    ]
