# Generated by Django 3.2.7 on 2021-09-16 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20210914_1639'),
        ('ops', '0030_weeklyprogramupdate_weeklyprogramupdatecommentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgramUpdateComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('comments', models.TextField(default='-')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_weeklyprogramupdatecomment_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='weeklyprogramupdate',
            options={'ordering': ('facility__name', 'operation_area', 'status')},
        ),
        migrations.DeleteModel(
            name='WeeklyProgramUpdateCommentLine',
        ),
        migrations.AddField(
            model_name='weeklyprogramupdatecomment',
            name='weekly_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.weeklyprogramupdate'),
        ),
    ]
