# Generated by Django 3.2.6 on 2021-10-14 07:00

from django.db import migrations, models
import django.db.models.deletion
import fahari.ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0030_auto_20211006_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreceiptverification',
            name='description',
        ),
        migrations.AlterField(
            model_name='stockreceiptverification',
            name='commodity',
            field=models.ForeignKey(default=fahari.ops.models.default_commodity, on_delete=django.db.models.deletion.PROTECT, to='ops.commodity', verbose_name='Commodity description'),
        ),
    ]
