# Generated by Django 3.2.7 on 2021-10-12 09:50

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0031_auto_20211010_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('operation_area', models.CharField(choices=[('admin', 'Administration'), ('finance', 'Finance'), ('awarding', 'Awarding'), ('subgranting', 'Subgranting'), ('sii', 'Strategic Information System'), ('program', 'Program')], default='program', help_text='Task Area of Operation', max_length=20)),
                ('attendees', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Use commas to separate attendee names', size=None)),
                ('visit_date', models.DateField(default=datetime.datetime.today)),
                ('checklist', models.ManyToManyField(to='ops.Checklist')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_mentorshipchecklist_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.DeleteModel(
            name='SiteMentorshipChecklist',
        ),
    ]
