# Generated by Django 3.2.6 on 2021-10-14 13:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_auto_20211014_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceiptverification',
            name='delivery_note_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stockreceiptverification',
            name='source',
            field=models.CharField(blank=True, choices=[('KEMSA', 'KEMSA'), ('MEDS', 'MEDS'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
