# Generated by Django 3.2.7 on 2021-09-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_auto_20210916_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogramupdatecomment',
            name='weekly_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates_comment', to='ops.weeklyprogramupdate'),
        ),
    ]
