# Generated by Django 3.2.6 on 2021-10-15 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_auto_20211014_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyprogramupdate',
            options={'ordering': ('title', 'operation_area', 'status')},
        ),
        migrations.RenameField(
            model_name='weeklyprogramupdatecomment',
            old_name='date_created',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weeklyprogramupdate',
            name='facility',
        ),
        migrations.AddField(
            model_name='weeklyprogramupdate',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='weeklyprogramupdate',
            name='title',
            field=models.CharField(default='-', max_length=255, verbose_name='Task title'),
        ),
    ]
