# Generated by Django 3.2.7 on 2021-09-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_alter_weeklyprogramupdatecomment_weekly_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyprogramupdatecomment',
            old_name='comments',
            new_name='comment',
        ),
    ]
