# Generated by Django 3.2.7 on 2021-10-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_auto_20211012_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('title', 'precedence')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'precedence')},
        ),
    ]
