# Generated by Django 3.2.7 on 2021-10-28 07:56

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0033_auto_20211015_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Section title')),
                ('precedence', models.IntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_groupsection_related', to='common.organisation')),
            ],
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('query', models.TextField(default='-', verbose_name='Question')),
                ('question_number', models.CharField(max_length=7, verbose_name='Question numbering')),
                ('answer_type', models.CharField(choices=[('true_false', 'True/False'), ('yes_no', 'Yes/No'), ('number', 'Number'), ('short_answer', 'Short answer'), ('paragraph', 'Long answer'), ('radio_option', 'Pick an option'), ('select_list', 'Check options')], default='short_answer', help_text='Answer type', max_length=15)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_question_related', to='common.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.question')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Group title')),
                ('precedence', models.IntegerField()),
                ('group_number', models.CharField(max_length=5, verbose_name='Question group numbering')),
                ('entry_date', models.DateField(default=datetime.datetime.today)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_questiongroup_related', to='common.organisation')),
                ('questions', models.ManyToManyField(to='ops.Question')),
            ],
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubgroupSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Subgroup title')),
                ('subgroup_number', models.CharField(max_length=5, verbose_name='Subgroup numbering')),
                ('precedence', models.IntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_subgroupsection_related', to='common.organisation')),
                ('question_groups', models.ManyToManyField(to='ops.QuestionGroup')),
            ],
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('answer_date', models.DateField(default=datetime.datetime.today)),
                ('response', models.CharField(max_length=255)),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_shortanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='SelectListAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('answer_date', models.DateField(default=datetime.datetime.today)),
                ('response', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, help_text='Select from the list', null=True, size=None)),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_selectlistanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='RadioOptionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('answer_date', models.DateField(default=datetime.datetime.today)),
                ('response', models.CharField(max_length=255)),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_radiooptionanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('answer_date', models.DateField(default=datetime.datetime.today)),
                ('response', models.TextField()),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_paragraphanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='NumberAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('answer_date', models.DateField(default=datetime.datetime.today)),
                ('response', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_numberanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('member_org', models.CharField(max_length=255, verbose_name='member organisation')),
                ('role', models.CharField(max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_mentorshipteammember_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('submit_date', models.DateField(default=datetime.datetime.today)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('group_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.groupsection')),
                ('mentorship_team', models.ManyToManyField(to='ops.MentorshipTeamMember')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_mentorshipquestionnaire_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='groupsection',
            name='sub_sections',
            field=models.ManyToManyField(to='ops.SubgroupSection'),
        ),
        migrations.CreateModel(
            name='BooleanAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('answer_date', models.DateField(default=datetime.datetime.today)),
                ('response', models.BooleanField()),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_booleananswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='subgroupsection',
            constraint=models.UniqueConstraint(fields=('precedence',), name='unique_subgroup_precedence'),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('precedence',), name='unique_questiongroup_precedence'),
        ),
        migrations.AddConstraint(
            model_name='groupsection',
            constraint=models.UniqueConstraint(fields=('precedence',), name='unique_group_precedence'),
        ),
    ]
