# Generated by Django 3.2.7 on 2021-10-22 09:28

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0033_auto_20211015_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Checklist title')),
                ('precedence', models.IntegerField()),
                ('entry_date', models.DateField(default=datetime.datetime.today, help_text='Filling visit date')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_checklist_related', to='common.organisation')),
            ],
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('question', models.TextField(default='-', verbose_name='Question')),
                ('question_number', models.CharField(max_length=7, verbose_name='Question numbering')),
                ('precedence', models.IntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_question_related', to='common.organisation')),
            ],
            options={
                'unique_together': {('question', 'precedence')},
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Questionnaire title')),
                ('precedence', models.IntegerField()),
                ('checklist', models.ManyToManyField(to='ops.Checklist')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_questionnaire_related', to='common.organisation')),
            ],
            options={
                'unique_together': {('title', 'precedence')},
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('response', models.CharField(default='-', help_text='Use yes/no OR true/false where applicable.', max_length=255)),
                ('comments', models.TextField(default='-', verbose_name='Comments')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_questionanswer_related', to='common.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.question')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('mentorship_team', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Use commas to separate team names', size=None)),
                ('visit_date', models.DateField(default=datetime.datetime.today, help_text='Site visit date')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_mentorshipchecklist_related', to='common.organisation')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.questionnaire')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='questions',
            field=models.ManyToManyField(to='ops.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('title', 'precedence')},
        ),
    ]
