# Generated by Django 3.2.9 on 2021-11-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0033_auto_20211015_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteMentorship',
        ),
    ]
