# Generated by Django 3.2.7 on 2021-10-13 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0033_auto_20211012_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipchecklist',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='mentorshipchecklist',
            name='visit_date',
            field=models.DateField(default=datetime.datetime.today, help_text='Site visit date'),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Questionnaire title')),
                ('precedence', models.IntegerField()),
                ('checklist', models.ManyToManyField(to='ops.Checklist')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_questionnaire_related', to='common.organisation')),
            ],
            options={
                'unique_together': {('title', 'precedence')},
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistFillStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('state', models.CharField(choices=[('introduction', 'Introduction'), ('preview', 'Preview'), ('antenatal_care', 'Antenatal Care'), ('postnatal_care', 'Postnatal care'), ('GMC', 'General matanity care'), ('hiv_testing', 'HIV Testing service'), ('care_and_treatment', 'Care and treatment analysis'), ('pediatric_file_analysis', 'Pediatric file analysis'), ('gender', 'Gender'), ('gbv_integration', 'Program'), ('adolescent_services', 'Adolescent services'), ('continuity_on_treatment', 'Continuity on treatment')], default='introduction', max_length=50)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_checklistfillstatus_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='mentorshipchecklist',
            name='questionnaire',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ops.questionnaire'),
            preserve_default=False,
        ),
    ]
