# Generated by Django 3.2.7 on 2021-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0033_auto_20211015_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogramupdate',
            name='operation_area',
            field=models.CharField(choices=[('admin_finance', 'Finance & Administration'), ('hiv_prevention', 'HIV Prevention services'), ('hiv_treatment', 'HIV Treatment services'), ('fp_rmncah', 'FP/RMNCAH'), ('nutrition', 'Nutrition'), ('wash', 'Water Sanitation Services'), ('logistics_inventory', 'County HSS: Logistics and inventory management'), ('surveillance', 'County HSS: Case based surveillance, public health response'), ('quality_improvement', 'County HSS: Quality improvement'), ('local_partners', "County HSS: Local partners' capacity"), ('community_engagement', 'County HSS: Engagement of the community')], default='hiv_prevention', help_text='Task Area of Operation', max_length=20),
        ),
    ]
