# Generated by Django 3.2.7 on 2021-09-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0033_rename_comments_weeklyprogramupdatecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogramupdatecomment',
            name='weekly_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.weeklyprogramupdate'),
        ),
    ]
