# Generated by Django 3.2.9 on 2021-11-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0034_alter_weeklyprogramupdate_operation_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteMentorship',
        ),
    ]
