# Generated by Django 3.2.7 on 2021-09-20 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0034_alter_weeklyprogramupdatecomment_weekly_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogramupdatecomment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
