# Generated by Django 3.2.7 on 2021-10-22 11:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0034_auto_20211022_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('mentorship_team', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Use commas to separate team names', size=None)),
                ('visit_date', models.DateField(default=datetime.datetime.today, help_text='Site visit date')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_mentorshipquestionnaire_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Group title')),
                ('precedence', models.IntegerField()),
                ('entry_date', models.DateField(default=datetime.datetime.today, help_text='Filling visit date')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_questiongroup_related', to='common.organisation')),
                ('questions', models.ManyToManyField(to='ops.Question')),
            ],
            options={
                'unique_together': {('title', 'precedence')},
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='mentorshipchecklist',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='mentorshipchecklist',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='mentorshipchecklist',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='MentorshipChecklist',
        ),
        migrations.AddField(
            model_name='mentorshipquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_groups',
            field=models.ManyToManyField(to='ops.QuestionGroup'),
        ),
    ]
