# Generated by Django 3.2.7 on 2021-10-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0034_auto_20211028_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('true_false', 'True/False'), ('yes_no', 'Yes/No'), ('number', 'Number'), ('short_answer', 'Short answer'), ('paragraph', 'Long answer'), ('radio_option', 'Pick an option'), ('select_list', 'Check options'), ('none', 'A parent question')], default='short_answer', help_text='Answer type', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, max_length=7, verbose_name='Question numbering'),
        ),
    ]
