# Generated by Django 3.2.7 on 2021-10-25 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0035_auto_20211022_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Group title')),
                ('precedence', models.IntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_groupsection_related', to='common.organisation')),
            ],
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.RenameField(
            model_name='mentorshipquestionnaire',
            old_name='visit_date',
            new_name='submit_date',
        ),
        migrations.RemoveField(
            model_name='mentorshipquestionnaire',
            name='questionnaire',
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='entry_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.AddField(
            model_name='groupsection',
            name='question_groups',
            field=models.ManyToManyField(to='ops.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='mentorshipquestionnaire',
            name='group_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.groupsection'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsection',
            unique_together={('title', 'precedence')},
        ),
    ]
