# Generated by Django 3.2.7 on 2021-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0036_auto_20211028_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsection',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorshipquestionnaire',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgroupsection',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
