# Generated by Django 3.2.7 on 2021-10-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0037_auto_20211028_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsection',
            name='sub_sections',
        ),
        migrations.AddField(
            model_name='groupsection',
            name='question_groups',
            field=models.ManyToManyField(to='ops.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='question_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='_ops_questiongroup_question_groups_+', to='ops.QuestionGroup'),
        ),
        migrations.DeleteModel(
            name='SubgroupSection',
        ),
    ]
