# Generated by Django 3.2.7 on 2021-10-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0037_auto_20211026_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongroup',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='groupsection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='groupsection',
            constraint=models.UniqueConstraint(fields=('precedence',), name='unique_group_precedence'),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('precedence',), name='unique_questiongroup_precedence'),
        ),
    ]
