# Generated by Django 3.2.7 on 2021-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0038_auto_20211029_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='question_groups',
            field=models.ManyToManyField(blank=True, related_name='_ops_questiongroup_question_groups_+', to='ops.QuestionGroup'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='questions',
            field=models.ManyToManyField(blank=True, to='ops.Question'),
        ),
    ]
