# Generated by Django 3.2.7 on 2021-10-26 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0038_auto_20211026_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsection',
            name='question_groups',
        ),
        migrations.AlterField(
            model_name='groupsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Section title'),
        ),
        migrations.CreateModel(
            name='SubgroupSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sub section title')),
                ('precedence', models.IntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_subgroupsection_related', to='common.organisation')),
                ('question_groups', models.ManyToManyField(to='ops.QuestionGroup')),
            ],
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='groupsection',
            name='sub_sections',
            field=models.ManyToManyField(to='ops.SubgroupSection'),
        ),
        migrations.AddConstraint(
            model_name='subgroupsection',
            constraint=models.UniqueConstraint(fields=('precedence',), name='unique_subgroup_precedence'),
        ),
    ]
