# Generated by Django 3.2.7 on 2021-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0039_auto_20211026_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='group_number',
            field=models.CharField(default='', max_length=5, verbose_name='Question group numbering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgroupsection',
            name='subgroup_number',
            field=models.CharField(default='', max_length=5, verbose_name='Subgroup numbering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subgroupsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Subgroup title'),
        ),
    ]
