# Generated by Django 3.2.7 on 2021-10-29 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0039_auto_20211029_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='group_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.groupsection'),
        ),
    ]
