# Generated by Django 3.2.7 on 2021-10-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0040_alter_mentorshipquestionnaire_group_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsection',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='mentorshipquestionnaire',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='is_complete',
        ),
    ]
