# Generated by Django 3.2.7 on 2021-10-27 08:07

from django.db import migrations, models
import django.utils.timezone
import fahari.common.models.base_models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0041_alter_question_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('organisation', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.DeleteModel(
            name='MentorshipTeam',
        ),
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='mentorship_team',
            field=models.ManyToManyField(to='ops.MentorshipTeamMember'),
        ),
    ]
