# Generated by Django 3.2.7 on 2021-11-02 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import fahari.common.models.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210919_1704'),
        ('ops', '0042_auto_20211101_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_questionnaire_related', to='common.organisation')),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('objects', fahari.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='mentorshipquestionnaire',
            name='group_section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='precedence',
        ),
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 10, 22, 44, 980855, tzinfo=utc), editable=False),
        ),
        migrations.DeleteModel(
            name='GroupSection',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='section',
            field=models.ManyToManyField(to='ops.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='mentorshipquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.questionnaire'),
        ),
    ]
