# Generated by Django 3.2.7 on 2021-11-02 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0043_auto_20211102_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 12, 35, 40, 842865, tzinfo=utc), editable=False),
        ),
    ]
