# Generated by Django 3.2.7 on 2021-11-08 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0045_auto_20211103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 7, 10, 51, 477056, tzinfo=utc), editable=False),
        ),
    ]
