# Generated by Django 3.2.7 on 2021-11-08 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0046_alter_mentorshipquestionnaire_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 58, 20, 488047, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 58, 32, 350599, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
