# Generated by Django 3.2.7 on 2021-11-08 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0047_auto_20211108_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 12, 25, 17, 870888, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
