# Generated by Django 3.2.7 on 2021-11-08 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0048_auto_20211108_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 12, 26, 48, 845031, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='mentorshipquestionnaire',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
