# Generated by Django 3.2.5 on 2021-07-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('name', '-updated')},
        ),
    ]
